import asyncio
from io import BytesIO

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Inches, Pt

COLORS = {
    "primary": RGBColor.from_string("2563EB"),
    "secondary": RGBColor.from_string("0F172A"),
    "text": RGBColor.from_string("334155"),
    "light": RGBColor.from_string("F8FAFC"),
    "border": RGBColor.from_string("E2E8F0"),
    "white": RGBColor.from_string("FFFFFF"),
    "muted": RGBColor.from_string("64748B"),
}
FONT = "Aptos"

SLIDE_W = 13.33
SLIDE_H = 7.5


def _blank_slide(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def _set_background(slide, color):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def _add_text(slide, text, x, y, w, h, *, size, color, bold=False, align=PP_ALIGN.LEFT, valign=None):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    frame = box.text_frame
    frame.word_wrap = True
    if valign is not None:
        frame.vertical_anchor = valign
    para = frame.paragraphs[0]
    para.alignment = align
    run = para.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.color.rgb = color
    run.font.bold = bold
    run.font.name = FONT
    return box


def _add_shape(slide, shape_type, x, y, w, h, fill, line):
    shape = slide.shapes.add_shape(
        shape_type, Inches(x), Inches(y), Inches(w), Inches(h)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill
    shape.line.color.rgb = line
    shape.shadow.inherit = False
    return shape


def _add_cover(data, prs):
    slide = _blank_slide(prs)
    _set_background(slide, COLORS["primary"])
    _add_shape(
        slide, MSO_SHAPE.RECTANGLE, 0, 0, SLIDE_W, 0.18,
        RGBColor.from_string("60A5FA"), RGBColor.from_string("60A5FA"),
    )
    _add_text(
        slide, data.get("title") or "Presentation Title", 0.7, 1.7, 12, 0.8,
        size=28, color=COLORS["white"], bold=True, align=PP_ALIGN.CENTER,
    )
    _add_text(
        slide, data.get("subtitle") or "Presentation Subtitle", 1, 2.8, 11.5, 0.4,
        size=15, color=RGBColor.from_string("DBEAFE"), align=PP_ALIGN.CENTER,
    )
    _add_text(
        slide, "Generated By GarvisAI", 0, 6.9, SLIDE_W, 0.2,
        size=10, color=RGBColor.from_string("BFDBFE"), align=PP_ALIGN.CENTER,
    )


def _add_content_slide(prs, title, points, slide_number, total_slides):
    slide = _blank_slide(prs)
    _set_background(slide, COLORS["white"])
    _add_text(
        slide, title or "Presentation Title", 0.6, 0.35, 10, 0.4,
        size=24, color=COLORS["primary"], bold=True,
    )
    line = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE, Inches(0.6), Inches(0.85), Inches(12), Pt(1.2)
    )
    line.fill.solid()
    line.fill.fore_color.rgb = RGBColor.from_string("60A5FA")
    line.line.color.rgb = RGBColor.from_string("60A5FA")
    line.shadow.inherit = False

    visible_points = (points or [])[:6]
    for index, point in enumerate(visible_points):
        y = 1.2 + index * 0.75
        _add_shape(
            slide, MSO_SHAPE.ROUNDED_RECTANGLE, 0.7, y, 12, 0.58,
            RGBColor.from_string("F8FAFC" if index % 2 else "EFF6FF"),
            COLORS["border"],
        )
        _add_shape(
            slide, MSO_SHAPE.OVAL, 0.92, y + 0.18, 0.12, 0.12,
            COLORS["primary"], COLORS["primary"],
        )
        _add_text(
            slide, point, 1.2, y + 0.08, 11, 0.35,
            size=15, color=COLORS["text"], valign=MSO_ANCHOR.MIDDLE,
        )
    _add_text(
        slide, f"{slide_number}/{total_slides}", 12.1, 6.9, 0.8, 0.2,
        size=10, color=COLORS["muted"], align=PP_ALIGN.RIGHT,
    )
    _add_text(
        slide, "GarvisAI", 0.6, 6.9, 2, 0.2,
        size=10, color=COLORS["muted"],
    )


def _add_thank_you(prs):
    slide = _blank_slide(prs)
    _set_background(slide, COLORS["secondary"])
    _add_text(
        slide, "Thank You", 0, 2.2, SLIDE_W, 0.8,
        size=34, color=COLORS["white"], bold=True, align=PP_ALIGN.CENTER,
    )
    _add_text(
        slide, "Generated By GarvisAI", 0, 6.9, SLIDE_W, 0.2,
        size=10, color=RGBColor.from_string("94A3B8"), align=PP_ALIGN.CENTER,
    )


def _build(data):
    """Same deck design as utils/generatePpt.js (pptxgenjs LAYOUT_WIDE)."""
    prs = Presentation()
    prs.slide_width = Inches(SLIDE_W)
    prs.slide_height = Inches(SLIDE_H)
    core = prs.core_properties
    core.author = "GarvisAI"
    core.title = data.get("title") or "PPTDocument"
    core.subject = data.get("title") or "PPTDocument"
    core.language = "en-US"

    _add_cover(data, prs)
    slides = data.get("slides") or []
    for index, slide_data in enumerate(slides):
        _add_content_slide(
            prs,
            slide_data.get("title"),
            slide_data.get("points"),
            index + 1,
            len(slides),
        )
    _add_thank_you(prs)

    buffer = BytesIO()
    prs.save(buffer)
    return buffer.getvalue()


async def generate_ppt(data):
    return await asyncio.to_thread(_build, data)
