# import asyncio
# from io import BytesIO

# from reportlab.lib.colors import HexColor
# from reportlab.lib.enums import TA_CENTER, TA_LEFT
# from reportlab.lib.pagesizes import A4
# from reportlab.lib.styles import ParagraphStyle
# from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

# TITLE = ParagraphStyle(
#     "Title", fontSize=28, leading=34, alignment=TA_CENTER, textColor=HexColor("#111827")
# )
# SUBTITLE = ParagraphStyle(
#     "Subtitle", fontSize=12, leading=15, alignment=TA_CENTER, textColor=HexColor("#6B7280")
# )
# HEADING = ParagraphStyle(
#     "Heading", fontSize=18, leading=23, alignment=TA_LEFT, textColor=HexColor("#111827")
# )
# POINT = ParagraphStyle(
#     "Point", fontSize=12, leading=17, alignment=TA_LEFT, textColor=HexColor("#374151")
# )
# FOOTER = ParagraphStyle(
#     "Footer", fontSize=10, leading=13, alignment=TA_CENTER, textColor=HexColor("#9CA3AF")
# )

# def clean_text(text: str) -> str:
#     if not text:
#         return ""

#     replacements = {
#         "\u00A0": " ",   # non-breaking space
#         "\u2009": " ",   # thin space
#         "\u200A": " ",   # hair space
#         "\u200B": "",    # zero-width space
#         "\u200C": "",    # zero-width non-joiner
#         "\u200D": "",    # zero-width joiner
#         "\u202F": " ",   # narrow no-break space
#         "\u2018": "'",   # left single quote
#         "\u2019": "'",   # right single quote
#         "\u201C": '"',   # left double quote
#         "\u201D": '"',   # right double quote
#         "\u2013": "-",   # en dash
#         "\u2014": "--",  # em dash
#     }

#     for old, new in replacements.items():
#         text = text.replace(old, new)

#     return text

# def _build(data):
#     """Same document layout as utils/generatePdf.js (pdfkit)."""
#     buffer = BytesIO()
#     doc = SimpleDocTemplate(
#         buffer,
#         pagesize=A4,
#         leftMargin=50,
#         rightMargin=50,
#         topMargin=50,
#         bottomMargin=50,
#         title=data.get("title") or "Document",
#         author="GarvisAI",
#         creator="GarvisAI",
#     )
#     story = [Paragraph(data.get("title") or "Document", TITLE)]
#     if data.get("subtitle"):
#         story.append(Spacer(1, 8))
#         story.append(Paragraph(data["subtitle"], SUBTITLE))
#     story.append(Spacer(1, 8))
#     for section in data.get("sections") or []:
#         story.append(Paragraph(section.get("heading") or "", HEADING))
#         story.append(Spacer(1, 8))
#         for point in section.get("points") or []:
#             story.append(Paragraph(f"• {point}", POINT))
#             story.append(Spacer(1, 4))
#         story.append(Spacer(1, 16))
#     story.append(Spacer(1, 16))
#     story.append(Paragraph("Generated by GarvisAI", FOOTER))
#     doc.build(story)
#     return buffer.getvalue()


# async def generate_pdf(data):
#     return await asyncio.to_thread(_build, data)

import asyncio
from io import BytesIO

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

TITLE = ParagraphStyle(
    "Title",
    fontSize=28,
    leading=34,
    alignment=TA_CENTER,
    textColor=HexColor("#111827"),
)

SUBTITLE = ParagraphStyle(
    "Subtitle",
    fontSize=12,
    leading=15,
    alignment=TA_CENTER,
    textColor=HexColor("#6B7280"),
)

HEADING = ParagraphStyle(
    "Heading",
    fontSize=18,
    leading=23,
    alignment=TA_LEFT,
    textColor=HexColor("#111827"),
)

POINT = ParagraphStyle(
    "Point",
    fontSize=12,
    leading=17,
    alignment=TA_LEFT,
    textColor=HexColor("#374151"),
)

FOOTER = ParagraphStyle(
    "Footer",
    fontSize=10,
    leading=13,
    alignment=TA_CENTER,
    textColor=HexColor("#9CA3AF"),
)


def clean_text(text: str) -> str:
    """Replace unsupported Unicode characters with safe ASCII equivalents."""
    if not text:
        return ""

    replacements = {
        "\u00A0": " ",   # Non-breaking space
        "\u2009": " ",   # Thin space
        "\u200A": " ",   # Hair space
        "\u200B": "",    # Zero-width space
        "\u200C": "",    # Zero-width non-joiner
        "\u200D": "",    # Zero-width joiner
        "\u202F": " ",   # Narrow no-break space
        "\u2018": "'",   # Left single quote
        "\u2019": "'",   # Right single quote
        "\u201C": '"',   # Left double quote
        "\u201D": '"',   # Right double quote
        "\u2013": "-",   # En dash
        "\u2014": "--",  # Em dash
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def _build(data):
    """Same document layout as utils/generatePdf.js (pdfkit)."""

    buffer = BytesIO()

    title = clean_text(data.get("title") or "Document")

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=50,
        rightMargin=50,
        topMargin=50,
        bottomMargin=50,
        title=title,
        author="GarvisAI",
        creator="GarvisAI",
    )

    story = [Paragraph(title, TITLE)]

    if data.get("subtitle"):
        story.append(Spacer(1, 8))
        story.append(Paragraph(clean_text(data["subtitle"]), SUBTITLE))

    story.append(Spacer(1, 8))

    for section in data.get("sections") or []:
        story.append(
            Paragraph(
                clean_text(section.get("heading") or ""),
                HEADING,
            )
        )
        story.append(Spacer(1, 8))

        for point in section.get("points") or []:
            story.append(
                Paragraph(
                    clean_text(point),
                    POINT,
                )
            )
            story.append(Spacer(1, 4))

        story.append(Spacer(1, 16))

    story.append(Spacer(1, 16))
    story.append(
        Paragraph(
            "Generated by GarvisAI",
            FOOTER,
        )
    )

    doc.build(story)

    return buffer.getvalue()


async def generate_pdf(data):
    return await asyncio.to_thread(_build, data)